export default class BinSize {
    #private;
    constructor([bits, prefixPower]: [number?, number?]);
    static fromBits(n: number): BinSize;
    static fromKilobits(n: number): BinSize;
    static fromMegabits(n: number): BinSize;
    static fromGigabits(n: number): BinSize;
    static fromTerabits(n: number): BinSize;
    static fromPetabits(n: number): BinSize;
    static fromExabits(n: number): BinSize;
    static fromZettabits(n: number): BinSize;
    static fromYottabits(n: number): BinSize;
    static fromBytes(n: number): BinSize;
    static fromKilobytes(n: number): BinSize;
    static fromMegabytes(n: number): BinSize;
    static fromGigabytes(n: number): BinSize;
    static fromTerabytes(n: number): BinSize;
    static fromPetabytes(n: number): BinSize;
    static fromExabytes(n: number): BinSize;
    static fromZettabytes(n: number): BinSize;
    static fromYottabytes(n: number): BinSize;
    static parse(s: string): BinSize;
    get bits(): number;
    get kilobits(): number;
    get megabits(): number;
    get gigabits(): number;
    get terabits(): number;
    get petabits(): number;
    get exabits(): number;
    get zettabits(): number;
    get yottabits(): number;
    get bytes(): number;
    get kilobytes(): number;
    get megabytes(): number;
    get gigabytes(): number;
    get terabytes(): number;
    get petabytes(): number;
    get exabytes(): number;
    get zettabytes(): number;
    get yottabytes(): number;
    toJSON(): number[];
    toString(parameters?: {
        whole?: boolean;
        fixed?: number;
        bytes?: boolean;
    }): string;
    add(b: BinSize): BinSize;
    substract(b: BinSize): BinSize;
    multiply(n: number): BinSize;
    divide(n: number): BinSize;
}
